# Generated by Django 3.0.2 on 2020-01-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20200118_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
