# Generated by Django 3.0.2 on 2020-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_auto_20200118_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='pay',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
