# Generated by Django 3.0.2 on 2020-01-19 01:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_jobpost_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
