# Generated by Django 3.0.2 on 2020-01-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_jobpost_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
